source "http://rubygems.org"

gem "capistrano", "~> 2.15.5"
gem "capistrano-multiconfig"
gem "magentify"

gem "capistrano_colors"
gem "capistrano-uptodate"
gem "capistrano-patch"
gem "capistrano-calendar"
